name = "p114514"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "ed-1"				#KV数据库id

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
